/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "./types";

export function Rocks(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/props.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.smallrock2_smallrocks_0.geometry}
        material={materials.smallrocks}
        material-roughness={0.2}
      />
    </group>
  );
}
