/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTFResult } from "./types";

export function Sign(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/props.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface7_Traffic_Signs_0001.geometry}
        material={materials.Traffic_Signs}
        position={[0, 0, 0.263]}
        scale={0.01}
        material-roughness={0.2}
      />
    </group>
  );
}
